stages:
  data_ingestion:
    cmd: python3 src/igfcnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/igfcnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Covid19-dataset
      

  prepare_base_model:
    cmd: python3 src/igfcnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/igfcnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

    
  training:
    cmd: python3 src/igfcnnClassifier/pipeline/stage_03_training.py
    deps:
      - src/igfcnnClassifier/pipeline/stage_03_training.py
      - src/igfcnnClassifier/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Covid19-dataset/train
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5