artifacts_root: artifacts

data_ingestion:

  root_dir: artifacts/data_ingestion
  source_URL: https://datasetsvinayak.s3.eu-north-1.amazonaws.com/covid_classification1.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



