artifacts_root: artifacts

data_ingestion:

  root_dir: artifacts/data_ingestion
  source_URL: https://datasetsvinayak.s3.eu-north-1.amazonaws.com/covid_classification1.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJ7%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRjBEAiBXeQK5SWUXggPb9qJ98uJQIOoyvgKLXAevUJ3lXtJV%2FAIgKAHLF9fVNNhrbYD6%2F60tYu7pge5ggMSMQHtAxrJ%2F5qkq5AIIRxACGgwxMDI3NzcyNDgzMjQiDEofmcmUrF2Al%2F8u4irBAi4FEF8K3OmVg9uTeiuH7ouEooDexeINKT2vz%2FHkjKraKUPGhXpnxa5eGsG70Z3MIGSRypu7BuQ%2B2G6QPJaZnOpOqIyCcYWr5jLoHIWS1uAdAEwrpl%2Fv8RaFavc2ElLhByxBecE1Yy4cV77oIMi9xisCtUJOB55pfTG7XIcDJInEszeSfiaWLzV73ySq%2BfJ1H2J5ATuYahGW0alMJu2pU%2F6n9GB3rMw7o0Ihgl2%2BwqdvCQtGpRylWDmWays%2Bnl2471tFMekB%2BOngrcYGje9Ia7%2FUd73sFdWZ7W1PHWvuuZBn0EdZJqupaYhYyG6CbwnS6W%2Bsx8J8m93VvReu6fczXt5jG9USHkjxuIteJXqwIFWWclLlKYcHJq%2Fmc1PN6SBN4ZiPftz42KRS3Y56wbK6LWFVdb%2B3EKmXFjIfqSfYkYEIDTCtobmmBjq0AiDWC7dxMyNoTZaOCD6NcDoucyCmtKRUwLgx6lOWz3cmjl%2FkjoLaiR0KjSIM4tOXbdFpg5beYDV0T%2Bss66iGAQaYCYRG7EJZe%2BsWkb9eCyS0qd7EfrtYIwMAsabEAWdXaTlnDmDyZn6dgmlE0LmfBxQ%2FhSdCGhoiys8cpNzsfySTmdv%2FLRQ0rr4oPpMYR0Sdvqv%2BtKOUD20%2FuWkxpjcx6Jc6SjI8O%2FfvCpPU%2FlA6wggE0oUo6W8oYYp3dFspIzLclslpu04CBeGfFu7NlVlup7s8Qgst%2F8tPv5zQF3SvQ5YNvmd0lfWJkEWCXvPd4vgYfxHAtgoQQfXO%2FaLKt30y%2FFWpP0gb%2BaB%2BhXvKdFM2piVvVOPPcMNrDI7xJQx7PiszIZjqUFBXIHr0gDP0Wk6GdfONRS9m&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230805T133818Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIARP3QALJCOFJBX3M2%2F20230805%2Feu-north-1%2Fs3%2Faws4_request&X-Amz-Signature=fcfd68da91a1d5d00ef3423464d6d1eaf35eaaf3939b1f7bf45c0e78bec04404
  local_data_file: artifacts/data_ingestion/covid_classification1.zip
  unzip_dir: artifacts/data_ingestion



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/model.h5




prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5